#!/bin/bash

# GitHub Secrets Setup Script for Klipit Pro CI/CD
# This script helps you add secrets to your GitHub Actions

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Klipit Pro - GitHub Secrets Setup Guide                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Repository: https://github.com/imabhisheks-dev/klipit-pro"
echo ""
echo "You need to add these secrets for CI/CD to work:"
echo ""
echo "1. SERVER_IP - Your Oracle Cloud server IP address"
echo "   Example: 123.45.67.89"
echo ""
echo "2. SERVER_USER - Ubuntu user (usually 'ubuntu')"
echo "   Example: ubuntu"
echo ""
echo "3. SERVER_SSH_KEY - Your private SSH key for server access"
echo "   (This file's content: cat ~/.ssh/id_ed25519)"
echo ""
echo "4. PROD_DATABASE_URL - Production PostgreSQL connection string"
echo "   Format: postgresql://user:password@host:5432/database"
echo ""
echo "5. DOCKER_USERNAME - Your Docker Hub username (optional)"
echo ""
echo "6. DOCKER_PASSWORD - Your Docker Hub access token (optional)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "Steps to add secrets:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Go to: https://github.com/imabhisheks-dev/klipit-pro/settings/secrets/actions"
echo ""
echo "2. Click 'New repository secret'"
echo ""
echo "3. Add each secret with 'Name' and 'Value'"
echo ""
echo "4. For SERVER_SSH_KEY, you can generate one:"
echo "   ssh-keygen -t ed25519 -C github-actions -f ~/.ssh/github-actions -N ''"
echo ""
echo "5. View your public key:"
echo "   cat ~/.ssh/github-actions.pub"
echo ""
echo "6. Add public key to server's ~/.ssh/authorized_keys:"
echo "   cat ~/.ssh/github-actions.pub | ssh ubuntu@SERVER_IP 'cat >> ~/.ssh/authorized_keys'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✓ Once all secrets are added, CI/CD will be ready to deploy!"
echo ""
